[build]
  # Build command to run during deployment
  command = "./build.sh"
  
  # Directory to publish (current directory since it's a static site)
  publish = "."
  
  # No install command needed for this static site
  ignore = "echo 'No install needed'"

[build.environment]
  # Default environment variables (can be overridden in Netlify dashboard)
  MISSIVE_API_BASE_URL = "https://public.missiveapp.com"
  MISSIVE_DEBUG_MODE = "false"
  MISSIVE_AUTO_ASSIGN = "true"

# Redirect rules (optional)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["!admin"]}

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 