[build]
  # Build command to run during deployment
  command = "node build.js"
  
  # Directory to publish (current directory since it's a static site)  
  publish = "."

[build.environment]
  # Default environment variables (can be overridden in Netlify dashboard)
  MISSIVE_API_BASE_URL = "https://public.missiveapp.com"
  MISSIVE_DEBUG_MODE = "false"
  MISSIVE_AUTO_ASSIGN = "true"

# Security headers - Allow embedding in Missive
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "frame-ancestors 'self' https://*.missiveapp.com https://mail.missiveapp.com" 